# Generated by Django 5.0.1 on 2026-01-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamGuidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="URL slug")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Guidance"),
                            ("ptsd", "PTSD"),
                            ("tbi", "Traumatic Brain Injury"),
                            (
                                "musculoskeletal",
                                "Musculoskeletal (Back, Knee, Shoulder)",
                            ),
                            ("hearing", "Hearing Loss / Tinnitus"),
                            ("respiratory", "Respiratory Conditions"),
                            ("sleep_apnea", "Sleep Apnea"),
                            ("mental_health", "Mental Health (non-PTSD)"),
                            ("other", "Other Conditions"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Brief overview of this exam type",
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "what_exam_measures",
                    models.TextField(
                        blank=True,
                        help_text="Plain-language explanation of DBQ form",
                        verbose_name="What This Exam Measures",
                    ),
                ),
                (
                    "physical_tests",
                    models.TextField(
                        blank=True,
                        help_text="Description of tests examiner will perform",
                        verbose_name="Physical Tests Performed",
                    ),
                ),
                (
                    "questions_to_expect",
                    models.TextField(
                        blank=True,
                        help_text="Sample questions examiner may ask",
                        verbose_name="Questions to Expect",
                    ),
                ),
                (
                    "preparation_tips",
                    models.TextField(
                        blank=True,
                        help_text="How to prepare (before exam)",
                        verbose_name="Preparation Tips",
                    ),
                ),
                (
                    "day_of_guidance",
                    models.TextField(
                        blank=True,
                        help_text="What to do on exam day",
                        verbose_name="Day-of Guidance",
                    ),
                ),
                (
                    "common_mistakes",
                    models.TextField(
                        blank=True,
                        help_text="What NOT to do",
                        verbose_name="Common Mistakes",
                    ),
                ),
                (
                    "after_exam",
                    models.TextField(
                        blank=True,
                        help_text="What to do post-exam",
                        verbose_name="After the Exam",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of preparation tasks",
                        verbose_name="Checklist Items",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display order")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="For SEO",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Guidance",
                "verbose_name_plural": "Exam Guidance",
                "ordering": ["order", "category", "title"],
            },
        ),
        migrations.CreateModel(
            name="ExamChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.CharField(
                        help_text="Condition for which exam is scheduled",
                        max_length=100,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(blank=True, null=True, verbose_name="Exam date"),
                ),
                (
                    "tasks_completed",
                    models.JSONField(
                        default=list,
                        help_text="List of task IDs that have been completed",
                        verbose_name="Completed tasks",
                    ),
                ),
                (
                    "symptom_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on symptoms to discuss",
                        verbose_name="Symptom Notes",
                    ),
                ),
                (
                    "worst_day_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of worst days with this condition",
                        verbose_name="Worst Day Description",
                    ),
                ),
                (
                    "functional_limitations",
                    models.TextField(
                        blank=True,
                        help_text="How condition affects daily life/work",
                        verbose_name="Functional Limitations",
                    ),
                ),
                (
                    "questions_for_examiner",
                    models.TextField(blank=True, verbose_name="Questions for Examiner"),
                ),
                (
                    "exam_completed",
                    models.BooleanField(default=False, verbose_name="Exam Completed"),
                ),
                (
                    "exam_notes",
                    models.TextField(
                        blank=True,
                        help_text="What happened during exam",
                        verbose_name="Post-Exam Notes",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="Reminder Sent"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guidance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated exam guidance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="examprep.examguidance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Checklist",
                "verbose_name_plural": "Exam Checklists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "term",
                    models.CharField(
                        help_text="Official VA term or acronym",
                        max_length=100,
                        unique=True,
                        verbose_name="VA Term",
                    ),
                ),
                (
                    "plain_language",
                    models.TextField(
                        help_text="Simple explanation anyone can understand",
                        verbose_name="Plain Language Definition",
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Additional context about importance",
                        verbose_name="When/Why This Matters",
                    ),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True,
                        help_text="Example usage or scenario",
                        verbose_name="Example",
                    ),
                ),
                (
                    "show_in_tooltips",
                    models.BooleanField(
                        default=True,
                        help_text="Display as inline tooltip when term appears",
                        verbose_name="Show in Tooltips",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display order")),
                (
                    "related_terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other terms related to this one",
                        to="examprep.glossaryterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Glossary Term",
                "verbose_name_plural": "Glossary Terms",
                "ordering": ["term"],
            },
        ),
    ]
