# Generated by Django 5.0.1 on 2026-01-10 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRatingCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Current Rating" or "If I add sleep apnea"',
                        max_length=100,
                        verbose_name="Calculation Name",
                    ),
                ),
                (
                    "ratings",
                    models.JSONField(
                        default=list,
                        help_text="List of individual disability ratings",
                        verbose_name="Disability Ratings",
                    ),
                ),
                (
                    "combined_raw",
                    models.FloatField(default=0, verbose_name="Combined (raw)"),
                ),
                (
                    "combined_rounded",
                    models.IntegerField(default=0, verbose_name="Combined (rounded)"),
                ),
                (
                    "bilateral_factor",
                    models.FloatField(default=0, verbose_name="Bilateral Factor"),
                ),
                (
                    "has_spouse",
                    models.BooleanField(default=False, verbose_name="Has Spouse"),
                ),
                (
                    "children_under_18",
                    models.IntegerField(default=0, verbose_name="Children Under 18"),
                ),
                (
                    "dependent_parents",
                    models.IntegerField(default=0, verbose_name="Dependent Parents"),
                ),
                (
                    "estimated_monthly",
                    models.FloatField(default=0, verbose_name="Estimated Monthly"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Rating Calculation",
                "verbose_name_plural": "Saved Rating Calculations",
                "ordering": ["-updated_at"],
            },
        ),
    ]
