# Generated by Django 5.0.1 on 2026-01-10 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_denial_decoding"),
        ("examprep", "0002_add_saved_rating_calculation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.CharField(
                        help_text="Medical condition this evidence is for",
                        max_length=200,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Claim"),
                            ("increase", "Rating Increase"),
                            ("secondary", "Secondary Condition"),
                            ("appeal", "Appeal / Supplemental Claim"),
                        ],
                        default="initial",
                        max_length=20,
                        verbose_name="Claim Type",
                    ),
                ),
                (
                    "primary_condition",
                    models.CharField(
                        blank=True,
                        help_text="For secondary claims: the primary service-connected condition",
                        max_length=200,
                        verbose_name="Primary Condition",
                    ),
                ),
                (
                    "m21_sections_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="M21 section references used in generation",
                        verbose_name="M21 Sections Used",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        default=list,
                        help_text="Evidence items with completion status",
                        verbose_name="Checklist Items",
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(default=0, verbose_name="Completion %"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="User notes about this evidence gathering",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "from_denial_analysis",
                    models.ForeignKey(
                        blank=True,
                        help_text="If generated from a denial analysis",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_checklists",
                        to="agents.decisionletteranalysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Checklist",
                "verbose_name_plural": "Evidence Checklists",
                "ordering": ["-updated_at"],
            },
        ),
    ]
