# Generated by Django 5.0.1 on 2026-01-12 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0003_evidence_checklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "share_token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique token for sharing this calculation",
                        max_length=32,
                        unique=True,
                        verbose_name="Share Token",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Shared VA Rating Calculation",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "ratings",
                    models.JSONField(
                        default=list,
                        help_text="List of individual disability ratings",
                        verbose_name="Disability Ratings",
                    ),
                ),
                (
                    "combined_raw",
                    models.FloatField(default=0, verbose_name="Combined (raw)"),
                ),
                (
                    "combined_rounded",
                    models.IntegerField(default=0, verbose_name="Combined (rounded)"),
                ),
                (
                    "bilateral_factor",
                    models.FloatField(default=0, verbose_name="Bilateral Factor"),
                ),
                (
                    "has_spouse",
                    models.BooleanField(default=False, verbose_name="Has Spouse"),
                ),
                (
                    "children_under_18",
                    models.IntegerField(default=0, verbose_name="Children Under 18"),
                ),
                (
                    "dependent_parents",
                    models.IntegerField(default=0, verbose_name="Dependent Parents"),
                ),
                (
                    "estimated_monthly",
                    models.FloatField(default=0, verbose_name="Estimated Monthly"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this share link expires",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "saved_calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="examprep.savedratingcalculation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Calculation",
                "verbose_name_plural": "Shared Calculations",
                "ordering": ["-created_at"],
            },
        ),
    ]
