# Generated by Django 5.0.1 on 2026-01-10 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("decision_analyzer", "Decision Letter Analyzer"),
                            ("evidence_gap", "Evidence Gap Analyzer"),
                            ("statement_generator", "Personal Statement Generator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DecisionLetterAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_text",
                    models.TextField(
                        help_text="Extracted or pasted text from decision letter"
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "conditions_granted",
                    models.JSONField(
                        default=list,
                        help_text="List of granted conditions with ratings",
                    ),
                ),
                (
                    "conditions_denied",
                    models.JSONField(
                        default=list, help_text="List of denied conditions with reasons"
                    ),
                ),
                (
                    "conditions_deferred",
                    models.JSONField(
                        default=list, help_text="List of deferred conditions"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Plain-English summary"),
                ),
                (
                    "appeal_options",
                    models.JSONField(
                        default=list, help_text="Available appeal paths with deadlines"
                    ),
                ),
                (
                    "evidence_issues",
                    models.JSONField(
                        default=list, help_text="Evidence problems identified"
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(default=list, help_text="Recommended next steps"),
                ),
                ("appeal_deadline", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked uploaded document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="claims.document",
                    ),
                ),
                (
                    "interaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_analysis",
                        to="agents.agentinteraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Letter Analysis",
                "verbose_name_plural": "Decision Letter Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceGapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_conditions",
                    models.JSONField(
                        default=list, help_text="Conditions being claimed"
                    ),
                ),
                (
                    "existing_evidence",
                    models.JSONField(
                        default=list, help_text="Evidence already gathered"
                    ),
                ),
                ("service_dates", models.CharField(blank=True, max_length=100)),
                ("service_branch", models.CharField(blank=True, max_length=50)),
                (
                    "evidence_gaps",
                    models.JSONField(default=list, help_text="Missing evidence items"),
                ),
                (
                    "strength_assessment",
                    models.JSONField(
                        default=dict, help_text="Current evidence strength by condition"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Prioritized recommendations"
                    ),
                ),
                (
                    "templates_suggested",
                    models.JSONField(
                        default=list, help_text="Relevant templates/forms"
                    ),
                ),
                (
                    "readiness_score",
                    models.IntegerField(
                        default=0, help_text="0-100 claim readiness score"
                    ),
                ),
                (
                    "interaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_analysis",
                        to="agents.agentinteraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Gap Analysis",
                "verbose_name_plural": "Evidence Gap Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.CharField(
                        help_text="Condition this statement supports", max_length=200
                    ),
                ),
                (
                    "in_service_event",
                    models.TextField(help_text="What happened during service"),
                ),
                (
                    "current_symptoms",
                    models.TextField(help_text="Current symptoms and limitations"),
                ),
                (
                    "daily_impact",
                    models.TextField(help_text="How condition affects daily life"),
                ),
                (
                    "work_impact",
                    models.TextField(
                        blank=True, help_text="How condition affects work"
                    ),
                ),
                (
                    "treatment_history",
                    models.TextField(blank=True, help_text="Treatment received"),
                ),
                (
                    "worst_days",
                    models.TextField(
                        blank=True, help_text="Description of worst days/flare-ups"
                    ),
                ),
                (
                    "generated_statement",
                    models.TextField(blank=True, help_text="AI-generated statement"),
                ),
                (
                    "final_statement",
                    models.TextField(blank=True, help_text="User-edited final version"),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Claim"),
                            ("increase", "Increase Request"),
                            ("secondary", "Secondary Condition"),
                            ("appeal", "Appeal Statement"),
                        ],
                        default="initial",
                        max_length=50,
                    ),
                ),
                (
                    "interaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_statement",
                        to="agents.agentinteraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Statement",
                "verbose_name_plural": "Personal Statements",
                "ordering": ["-created_at"],
            },
        ),
    ]
