# Generated by Django 5.0.1 on 2026-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="M21ScrapeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target_parts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Which parts to scrape (empty = all)",
                        verbose_name="Target Parts",
                    ),
                ),
                (
                    "force_update",
                    models.BooleanField(
                        default=False,
                        help_text="Re-scrape even if content exists",
                        verbose_name="Force Update",
                    ),
                ),
                (
                    "total_sections",
                    models.IntegerField(default=0, verbose_name="Total Sections"),
                ),
                (
                    "sections_completed",
                    models.IntegerField(default=0, verbose_name="Sections Completed"),
                ),
                (
                    "sections_failed",
                    models.IntegerField(default=0, verbose_name="Sections Failed"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                ("error_log", models.TextField(blank=True, verbose_name="Error Log")),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of what was scraped",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="Duration (seconds)"),
                ),
            ],
            options={
                "verbose_name": "M21 Scrape Job",
                "verbose_name_plural": "M21 Scrape Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="M21ManualSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "part",
                    models.CharField(
                        help_text="Part number: I, II, III, etc.",
                        max_length=10,
                        verbose_name="Part (Roman numeral)",
                    ),
                ),
                (
                    "part_number",
                    models.IntegerField(
                        help_text="Numeric version of part for sorting",
                        verbose_name="Part (integer)",
                    ),
                ),
                (
                    "part_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Part Title"
                    ),
                ),
                (
                    "subpart",
                    models.CharField(
                        help_text="Subpart: i, ii, iii, etc.",
                        max_length=10,
                        verbose_name="Subpart (lowercase Roman)",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        help_text="Chapter number",
                        max_length=10,
                        verbose_name="Chapter",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Section letter: A, B, C, etc.",
                        max_length=5,
                        verbose_name="Section (Letter)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Section Title"),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Format: M21-1.I.i.1.A",
                        max_length=50,
                        unique=True,
                        verbose_name="Reference Code",
                    ),
                ),
                (
                    "full_reference",
                    models.CharField(
                        blank=True,
                        help_text="Format: M21-1, Part I, Subpart i, Chapter 1, Section A",
                        max_length=200,
                        verbose_name="Full Reference",
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="Introduction/overview of this section",
                        verbose_name="Overview",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Complete section content in HTML/markdown",
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured topics within this section",
                        verbose_name="Topics",
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Referenced M21-1 sections and CFR citations",
                        verbose_name="Cross References",
                    ),
                ),
                (
                    "article_id",
                    models.CharField(
                        blank=True,
                        help_text="Original KnowVA article identifier",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="KnowVA Article ID",
                    ),
                ),
                (
                    "knowva_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="KnowVA URL"
                    ),
                ),
                (
                    "last_updated_va",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last updated date from KnowVA",
                        null=True,
                        verbose_name="Last Updated (VA)",
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When we scraped this content",
                        verbose_name="Scraped At",
                    ),
                ),
                (
                    "last_scraped",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time we updated this from KnowVA",
                        verbose_name="Last Scraped",
                    ),
                ),
                (
                    "scrape_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("stale", "Stale (needs update)"),
                            ("pending", "Pending"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="Scrape Status",
                    ),
                ),
                (
                    "scrape_error",
                    models.TextField(blank=True, verbose_name="Scrape Error"),
                ),
                (
                    "search_text",
                    models.TextField(
                        blank=True,
                        help_text="Denormalized full text for search",
                        verbose_name="Search Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "M21-1 Manual Section",
                "verbose_name_plural": "M21-1 Manual Sections",
                "ordering": ["part_number", "subpart", "chapter", "section"],
                "indexes": [
                    models.Index(
                        fields=["part_number", "subpart", "chapter", "section"],
                        name="agents_m21m_part_nu_8afafa_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="agents_m21m_referen_cc8a01_idx"
                    ),
                    models.Index(
                        fields=["article_id"], name="agents_m21m_article_7389e2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="M21TopicIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("service_connection", "Service Connection"),
                            ("rating_process", "Rating Process"),
                            ("evidence", "Evidence Requirements"),
                            ("examinations", "C&P Examinations"),
                            ("effective_dates", "Effective Dates"),
                            ("appeals", "Appeals Process"),
                            ("mental_health", "Mental Health Conditions"),
                            ("musculoskeletal", "Musculoskeletal Conditions"),
                            (
                                "special_monthly_compensation",
                                "Special Monthly Compensation (SMC)",
                            ),
                            (
                                "tdiu",
                                "Total Disability Individual Unemployability (TDIU)",
                            ),
                            ("presumptive", "Presumptive Service Connection"),
                            ("secondary", "Secondary Service Connection"),
                            ("nexus", "Nexus / Medical Opinion"),
                            ("duty_to_assist", "Duty to Assist"),
                            ("errors", "Clear and Unmistakable Error (CUE)"),
                            ("dependents", "Dependents and Dependency"),
                            ("combined_ratings", "Combined Ratings"),
                            ("extraschedular", "Extraschedular Ratings"),
                        ],
                        max_length=50,
                        verbose_name="Topic",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Topic Title")),
                (
                    "description",
                    models.TextField(
                        help_text="What this topic covers", verbose_name="Description"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords used to identify relevant sections",
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority topics shown first to agents",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="topic_indices",
                        to="agents.m21manualsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "M21 Topic Index",
                "verbose_name_plural": "M21 Topic Indices",
                "ordering": ["-priority", "topic"],
            },
        ),
    ]
