# Generated by Django 5.0.1 on 2026-01-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_m21scrapejob_m21manualsection_m21topicindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenialDecoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "denial_mappings",
                    models.JSONField(
                        default=list,
                        help_text="Denials with M21 matches and evidence requirements",
                        verbose_name="Denial Mappings",
                    ),
                ),
                (
                    "evidence_strategy",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated overall strategy for addressing denials",
                        verbose_name="Evidence Strategy",
                    ),
                ),
                (
                    "priority_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recommended order to address denials",
                        verbose_name="Priority Order",
                    ),
                ),
                (
                    "m21_sections_searched",
                    models.IntegerField(
                        default=0,
                        help_text="Number of M21 sections searched",
                        verbose_name="M21 Sections Searched",
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        default=0,
                        help_text="Time taken to decode denials",
                        verbose_name="Processing Time",
                    ),
                ),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denial_decoding",
                        to="agents.decisionletteranalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denial Decoding",
                "verbose_name_plural": "Denial Decodings",
                "ordering": ["-created_at"],
            },
        ),
    ]
