# Generated by Django 5.0.1 on 2026-01-18 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_denial_decoding"),
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinteraction",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("decision_analyzer", "Decision Letter Analyzer"),
                    ("evidence_gap", "Evidence Gap Analyzer"),
                    ("statement_generator", "Personal Statement Generator"),
                    ("rating_analyzer", "Rating Decision Analyzer"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RatingAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_text",
                    models.TextField(
                        help_text="OCR-extracted text from rating decision"
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("veteran_name", models.CharField(blank=True, max_length=200)),
                ("file_number", models.CharField(blank=True, max_length=50)),
                (
                    "combined_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Combined disability rating percentage",
                        null=True,
                    ),
                ),
                (
                    "monthly_compensation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly compensation amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list,
                        help_text="List of conditions with ratings and diagnostic codes",
                        verbose_name="Rated Conditions",
                    ),
                ),
                (
                    "evidence_list",
                    models.JSONField(
                        default=list,
                        help_text="List of evidence VA reviewed",
                        verbose_name="Evidence Reviewed",
                    ),
                ),
                (
                    "increase_opportunities",
                    models.JSONField(
                        default=list,
                        help_text="Opportunities to increase ratings for each condition",
                        verbose_name="Increase Opportunities",
                    ),
                ),
                (
                    "secondary_conditions",
                    models.JSONField(
                        default=list,
                        help_text="Potential secondary conditions to claim",
                        verbose_name="Secondary Conditions",
                    ),
                ),
                (
                    "rating_errors",
                    models.JSONField(
                        default=list,
                        help_text="Potential errors in the rating decision",
                        verbose_name="Potential Rating Errors",
                    ),
                ),
                (
                    "effective_date_issues",
                    models.JSONField(
                        default=list,
                        help_text="Potential issues with effective dates",
                        verbose_name="Effective Date Issues",
                    ),
                ),
                (
                    "deadline_tracker",
                    models.JSONField(
                        default=dict,
                        help_text="Appeal deadlines and availability",
                        verbose_name="Deadline Tracker",
                    ),
                ),
                (
                    "benefits_unlocked",
                    models.JSONField(
                        default=list,
                        help_text="Benefits veteran is eligible for at current rating",
                        verbose_name="Benefits Unlocked",
                    ),
                ),
                (
                    "exam_prep_tips",
                    models.JSONField(
                        default=list,
                        help_text="C&P exam preparation guidance",
                        verbose_name="Exam Prep Tips",
                    ),
                ),
                (
                    "priority_actions",
                    models.JSONField(
                        default=list,
                        help_text="Prioritized list of recommended actions",
                        verbose_name="Priority Actions",
                    ),
                ),
                (
                    "markdown_analysis",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable markdown-formatted analysis",
                        verbose_name="Markdown Analysis",
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        default=0,
                        help_text="Time taken to analyze the rating decision",
                        verbose_name="Processing Time",
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Total OpenAI tokens used",
                        verbose_name="Tokens Used",
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated API cost",
                        max_digits=10,
                        verbose_name="Cost Estimate",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked uploaded document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="claims.document",
                    ),
                ),
                (
                    "interaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_analysis",
                        to="agents.agentinteraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating Analysis",
                "verbose_name_plural": "Rating Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
