# Generated by Django 5.0.1 on 2026-01-18 01:16

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_add_rating_analysis_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratinganalysis",
            name="file_number",
            field=core.encryption.EncryptedCharField(
                blank=True, help_text="VA file number (encrypted)", max_length=255
            ),
        ),
    ]
