# Generated by Django 5.0.1 on 2026-01-18 01:16
"""
Data migration to encrypt existing file_number data in RatingAnalysis.
"""

from django.db import migrations


def encrypt_existing_data(apps, schema_editor):
    """
    Encrypt existing file_number data that may have been stored unencrypted.
    """
    from core.encryption import FieldEncryption
    from django.db import connection

    with connection.cursor() as cursor:
        # Encrypt file_number in RatingAnalysis
        cursor.execute("""
            SELECT id, file_number
            FROM agents_ratinganalysis
            WHERE file_number IS NOT NULL
            AND file_number != ''
            AND length(file_number) < 100
        """)
        for analysis_id, file_number in cursor.fetchall():
            encrypted = FieldEncryption.encrypt(file_number)
            cursor.execute(
                "UPDATE agents_ratinganalysis SET file_number = %s WHERE id = %s",
                [encrypted, analysis_id]
            )


def decrypt_data(apps, schema_editor):
    """
    Reverse migration - decrypt data back to plain text.
    """
    from core.encryption import FieldEncryption
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, file_number
            FROM agents_ratinganalysis
            WHERE file_number IS NOT NULL
            AND file_number != ''
            AND length(file_number) > 100
        """)
        for analysis_id, file_number in cursor.fetchall():
            decrypted = FieldEncryption.decrypt(file_number)
            if decrypted:
                cursor.execute(
                    "UPDATE agents_ratinganalysis SET file_number = %s WHERE id = %s",
                    [decrypted, analysis_id]
                )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_encrypt_pii_fields"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_data, decrypt_data),
    ]
