# Generated by Django 5.0.1 on 2026-01-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_encrypt_existing_file_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratinganalysis",
            name="confidence_breakdown",
            field=models.JSONField(
                default=dict,
                help_text="Detailed confidence scores for different aspects",
                verbose_name="Confidence Breakdown",
            ),
        ),
        migrations.AddField(
            model_name="ratinganalysis",
            name="confidence_factors",
            field=models.JSONField(
                default=list,
                help_text="Factors that influenced confidence scoring",
                verbose_name="Confidence Factors",
            ),
        ),
        migrations.AddField(
            model_name="ratinganalysis",
            name="overall_confidence",
            field=models.IntegerField(
                default=0,
                help_text="AI confidence score for overall analysis quality (0-100)",
                verbose_name="Overall Confidence",
            ),
        ),
    ]
