# Generated by Django 5.0.1 on 2026-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_add_confidence_scoring"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisionletteranalysis",
            name="raw_text",
        ),
        migrations.RemoveField(
            model_name="ratinganalysis",
            name="raw_text",
        ),
    ]
