domains:
- domain: vabenefitsnavigator.org
  type: PRIMARY
- domain: www.vabenefitsnavigator.org
  type: ALIAS
envs:
- key: DJANGO_SETTINGS_MODULE
  scope: RUN_AND_BUILD_TIME
  value: benefits_navigator.settings
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "False"
- key: USE_S3
  scope: RUN_AND_BUILD_TIME
  value: "False"
- key: STAGING
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: "-WAK9v6CH4eNU45REU8928FmKIL32HTq45p4n3szCmyTRVKHGhj-qbc_YrnLomI5MdM"
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: "postgresql://doadmin:show-password@benefits-nav-db-do-user-29214045-0.j.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  value: "rediss://default:show-password@db-valkey-nyc3-98037-do-user-29214045-0.k.db.ondigitalocean.com:25061"
- key: CELERY_BROKER_URL
  scope: RUN_AND_BUILD_TIME
  value: "rediss://default:show-password@db-valkey-nyc3-98037-do-user-29214045-0.k.db.ondigitalocean.com:25061"
- key: OPENAI_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: SENTRY_DSN
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: FIELD_ENCRYPTION_KEY
  scope: RUN_AND_BUILD_TIME
  value: "b9c5AxhQMmoCGhEaicz-8iaen0rln_Wehs6z4XXCoz0="
- key: PILOT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: PILOT_BILLING_DISABLED
  scope: RUN_AND_BUILD_TIME
  value: "True"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
jobs:
- dockerfile_path: Dockerfile.prod
  envs:
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "-WAK9v6CH4eNU45REU8928FmKIL32HTq45p4n3szCmyTRVKHGhj-qbc_YrnLomI5MdM"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "postgresql://doadmin:show-password@benefits-nav-db-do-user-29214045-0.j.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
  - key: FIELD_ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "b9c5AxhQMmoCGhEaicz-8iaen0rln_Wehs6z4XXCoz0="
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "benefits-navigator-staging-3o4rq.ondigitalocean.app,vabenefitsnavigator.org,www.vabenefitsnavigator.org,localhost"
  github:
    branch: main
    deploy_on_push: true
    repo: Beaudoin0zach/benefits_navigator
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: migrate
  run_command: /bin/sh -c "python manage.py migrate --noinput; exit 0"
name: benefits-navigator-staging
region: nyc
services:
- dockerfile_path: Dockerfile.prod
  envs:
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "benefits-navigator-staging-3o4rq.ondigitalocean.app,vabenefitsnavigator.org,www.vabenefitsnavigator.org,localhost"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "-WAK9v6CH4eNU45REU8928FmKIL32HTq45p4n3szCmyTRVKHGhj-qbc_YrnLomI5MdM"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "postgresql://doadmin:show-password@benefits-nav-db-do-user-29214045-0.j.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: "rediss://default:show-password@db-valkey-nyc3-98037-do-user-29214045-0.k.db.ondigitalocean.com:25061"
  - key: FIELD_ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "b9c5AxhQMmoCGhEaicz-8iaen0rln_Wehs6z4XXCoz0="
  github:
    branch: main
    deploy_on_push: true
    repo: Beaudoin0zach/benefits_navigator
  health_check:
    http_path: /health/
    initial_delay_seconds: 30
    period_seconds: 10
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
workers:
- dockerfile_path: Dockerfile.prod
  envs:
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: "benefits_navigator.settings"
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: STAGING
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "benefits-navigator-staging-3o4rq.ondigitalocean.app,vabenefitsnavigator.org,www.vabenefitsnavigator.org,localhost"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "-WAK9v6CH4eNU45REU8928FmKIL32HTq45p4n3szCmyTRVKHGhj-qbc_YrnLomI5MdM"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "postgresql://doadmin:show-password@benefits-nav-db-do-user-29214045-0.j.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: "rediss://default:show-password@db-valkey-nyc3-98037-do-user-29214045-0.k.db.ondigitalocean.com:25061"
  - key: CELERY_BROKER_URL
    scope: RUN_AND_BUILD_TIME
    value: "rediss://default:show-password@db-valkey-nyc3-98037-do-user-29214045-0.k.db.ondigitalocean.com:25061"
  - key: FIELD_ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "b9c5AxhQMmoCGhEaicz-8iaen0rln_Wehs6z4XXCoz0="
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ""
  github:
    branch: main
    deploy_on_push: true
    repo: Beaudoin0zach/benefits_navigator
  instance_count: 1
  instance_size_slug: basic-xxs
  name: worker
  run_command: celery -A benefits_navigator worker --loglevel info --concurrency 1
