domains:
- domain: vabenefitsnavigator.org
  type: PRIMARY
- domain: www.vabenefitsnavigator.org
  type: ALIAS
envs:
- key: DJANGO_SETTINGS_MODULE
  scope: RUN_AND_BUILD_TIME
  value: benefits_navigator.settings
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "False"
- key: USE_S3
  scope: RUN_AND_BUILD_TIME
  value: "False"
- key: STAGING
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: "***ROTATED_SECRET_KEY***"
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: "***ROTATED_DATABASE_URL***"
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  value: "***ROTATED_REDIS_URL***"
- key: CELERY_BROKER_URL
  scope: RUN_AND_BUILD_TIME
  value: "***ROTATED_REDIS_URL***"
- key: OPENAI_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: SENTRY_DSN
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: FIELD_ENCRYPTION_KEY
  scope: RUN_AND_BUILD_TIME
  value: "***ROTATED_FIELD_ENCRYPTION_KEY***"
- key: PILOT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: PILOT_BILLING_DISABLED
  scope: RUN_AND_BUILD_TIME
  value: "True"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
jobs:
- dockerfile_path: Dockerfile.prod
  envs:
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_SECRET_KEY***"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_DATABASE_URL***"
  - key: FIELD_ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_FIELD_ENCRYPTION_KEY***"
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "benefits-navigator-staging-3o4rq.ondigitalocean.app,vabenefitsnavigator.org,www.vabenefitsnavigator.org,localhost"
  github:
    branch: main
    deploy_on_push: true
    repo: Beaudoin0zach/benefits_navigator
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: migrate
  run_command: /bin/sh -c "python manage.py migrate --noinput; exit 0"
name: benefits-navigator-staging
region: nyc
services:
- dockerfile_path: Dockerfile.prod
  envs:
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "benefits-navigator-staging-3o4rq.ondigitalocean.app,vabenefitsnavigator.org,www.vabenefitsnavigator.org,localhost"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_SECRET_KEY***"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_DATABASE_URL***"
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_REDIS_URL***"
  - key: FIELD_ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_FIELD_ENCRYPTION_KEY***"
  github:
    branch: main
    deploy_on_push: true
    repo: Beaudoin0zach/benefits_navigator
  health_check:
    http_path: /health/
    initial_delay_seconds: 30
    period_seconds: 10
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
workers:
- dockerfile_path: Dockerfile.prod
  envs:
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: "benefits_navigator.settings"
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: STAGING
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "benefits-navigator-staging-3o4rq.ondigitalocean.app,vabenefitsnavigator.org,www.vabenefitsnavigator.org,localhost"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_SECRET_KEY***"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_DATABASE_URL***"
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_REDIS_URL***"
  - key: CELERY_BROKER_URL
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_REDIS_URL***"
  - key: FIELD_ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "***ROTATED_FIELD_ENCRYPTION_KEY***"
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ""
  github:
    branch: main
    deploy_on_push: true
    repo: Beaudoin0zach/benefits_navigator
  instance_count: 1
  instance_size_slug: basic-xxs
  name: worker
  run_command: celery -A benefits_navigator worker --loglevel info --concurrency 1
