# Generated by Django 5.0.1 on 2026-01-10 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appeals", "0001_initial"),
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier (e.g., claim_filed, exam_scheduled)",
                        max_length=30,
                        unique=True,
                        verbose_name="Stage Code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Stage Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in the journey timeline",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "typical_duration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected time at this stage",
                        null=True,
                        verbose_name="Typical Duration (days)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("clipboard", "Clipboard"),
                            ("calendar", "Calendar"),
                            ("check", "Check"),
                            ("clock", "Clock"),
                            ("mail", "Mail"),
                            ("flag", "Flag"),
                            ("alert", "Alert"),
                        ],
                        default="document",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                            ("gray", "Gray"),
                        ],
                        default="blue",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Stage",
                "verbose_name_plural": "Journey Stages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("deadline_date", models.DateField(verbose_name="Deadline Date")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="Reminder Sent"),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deadlines",
                        to="appeals.appeal",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deadlines",
                        to="claims.claim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deadline",
                "verbose_name_plural": "Deadlines",
                "ordering": ["deadline_date"],
            },
        ),
        migrations.CreateModel(
            name="JourneyMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("claim_filed", "Claim Filed"),
                            ("exam_scheduled", "C&P Exam Scheduled"),
                            ("exam_completed", "C&P Exam Completed"),
                            ("decision_received", "Decision Received"),
                            ("rating_assigned", "Rating Assigned"),
                            ("appeal_filed", "Appeal Filed"),
                            ("appeal_won", "Appeal Won"),
                            ("increase_granted", "Increase Granted"),
                            ("100_percent", "100% Rating Achieved"),
                            ("tdiu_granted", "TDIU Granted"),
                            ("custom", "Custom Milestone"),
                        ],
                        max_length=30,
                        verbose_name="Milestone Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional milestone data (e.g., rating percentage)",
                        verbose_name="Details",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Milestone",
                "verbose_name_plural": "Journey Milestones",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserJourneyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic (System)"),
                            ("manual", "Manual (User)"),
                            ("system", "System Notification"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Event Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("event_date", models.DateField(verbose_name="Event Date")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event data",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journey_events",
                        to="appeals.appeal",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journey_events",
                        to="claims.claim",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.journeystage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Event",
                "verbose_name_plural": "Journey Events",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
    ]
