# Generated by Django 5.0.1 on 2026-01-10 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_journey_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("audit_logs", "Audit Logs"),
                            ("documents", "Documents"),
                            ("analyses", "AI Analyses"),
                            ("session_data", "Session Data"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Data Type",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        help_text="Number of days to retain data (0 = indefinite)",
                        verbose_name="Retention Days",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_cleanup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Cleanup"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="Preserved email if user deleted",
                        max_length=254,
                        verbose_name="User Email",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("document_upload", "Document Upload"),
                            ("document_view", "Document View"),
                            ("document_download", "Document Download"),
                            ("document_delete", "Document Delete"),
                            ("pii_view", "PII View"),
                            ("pii_export", "PII Export"),
                            ("ai_analysis", "AI Analysis"),
                            ("denial_decode", "Denial Decode"),
                            ("profile_update", "Profile Update"),
                            ("account_delete", "Account Delete Request"),
                            ("admin_action", "Admin Action"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Request Path"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Request Method"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Document, Appeal, Claim",
                        max_length=50,
                        verbose_name="Resource Type",
                    ),
                ),
                (
                    "resource_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Resource ID"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional action-specific data",
                        verbose_name="Details",
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_auditl_user_id_7b678c_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="core_auditl_action_096de0_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                ],
            },
        ),
    ]
