# Generated by Django 5.0.1 on 2026-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportiveMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("dashboard_welcome", "Dashboard Welcome"),
                            ("dashboard_progress", "Dashboard Progress"),
                            ("exam_starting", "Starting Exam Prep"),
                            ("exam_progress_25", "Exam Prep 25% Complete"),
                            ("exam_progress_50", "Exam Prep 50% Complete"),
                            ("exam_progress_75", "Exam Prep 75% Complete"),
                            ("exam_ready", "Exam Prep Complete"),
                            ("exam_upcoming_7_days", "Exam in 7 Days"),
                            ("exam_upcoming_tomorrow", "Exam Tomorrow"),
                            ("exam_completed", "Exam Completed"),
                            ("claim_filed", "Claim Filed"),
                            ("claim_pending", "Claim Pending Review"),
                            ("claim_waiting", "Long Wait Encouragement"),
                            ("decision_granted", "Claim Granted"),
                            ("decision_denied", "Claim Denied"),
                            ("decision_partial", "Partial Grant"),
                            ("appeal_starting", "Starting Appeal"),
                            ("appeal_filed", "Appeal Filed"),
                            ("appeal_pending", "Appeal Pending"),
                            ("deadline_30_days", "Deadline in 30 Days"),
                            ("deadline_7_days", "Deadline in 7 Days"),
                            ("deadline_urgent", "Deadline Urgent"),
                            ("milestone_achieved", "Milestone Achieved"),
                            ("first_login", "First Login"),
                            ("evidence_uploaded", "Evidence Uploaded"),
                            ("evidence_gap_found", "Evidence Gap Identified"),
                            ("general", "General Encouragement"),
                        ],
                        db_index=True,
                        help_text="When this message should be displayed",
                        max_length=30,
                        verbose_name="Context",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The supportive message text (supports markdown)",
                        verbose_name="Message",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("encouraging", "Encouraging"),
                            ("informative", "Informative"),
                            ("celebratory", "Celebratory"),
                            ("urgent", "Urgent"),
                            ("calming", "Calming"),
                        ],
                        default="encouraging",
                        max_length=20,
                        verbose_name="Tone",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="heart",
                        help_text="Icon name (e.g., heart, star, flag, shield)",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower = higher priority)",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supportive Message",
                "verbose_name_plural": "Supportive Messages",
                "ordering": ["context", "order"],
            },
        ),
    ]
