# Generated by Django 5.0.1 on 2026-01-12 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_supportive_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_url", models.CharField(max_length=500, verbose_name="Page URL")),
                (
                    "page_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Page Title"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("positive", "Positive (Thumbs Up)"),
                            ("negative", "Negative (Thumbs Down)"),
                            ("neutral", "Neutral"),
                        ],
                        help_text="Quick thumbs up/down rating",
                        max_length=10,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Feedback"),
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("content", "Content Issue"),
                            ("usability", "Usability"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed feedback",
                        verbose_name="Comment",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Session Key"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("addressed", "Addressed"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin Notes"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
