# Generated by Django 5.0.1 on 2026-01-12 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_feedback_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Question"),
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("account", "Account Issue"),
                            ("billing", "Billing Question"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Page URL"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("waiting", "Waiting for Response"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin Notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Request",
                "verbose_name_plural": "Support Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
