# Generated by Django 5.0.1 on 2026-01-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_support_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "failure_type",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR Failure"),
                            ("ai_analysis", "AI Analysis Failure"),
                            ("timeout", "Processing Timeout"),
                            ("file_error", "File Error"),
                            ("unknown", "Unknown Error"),
                        ],
                        max_length=20,
                        verbose_name="Failure Type",
                    ),
                ),
                (
                    "document_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Document ID"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Celery Task ID"
                    ),
                ),
                ("error_message", models.TextField(verbose_name="Error Message")),
                (
                    "stack_trace",
                    models.TextField(blank=True, verbose_name="Stack Trace"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution Notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "alert_sent",
                    models.BooleanField(default=False, verbose_name="Alert Sent"),
                ),
                (
                    "alert_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Alert Sent At"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_failures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Failure",
                "verbose_name_plural": "Processing Failures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("celery_queue", "Celery Queue Length"),
                            ("celery_workers", "Celery Active Workers"),
                            ("document_processing", "Document Processing"),
                            ("ocr_success", "OCR Success Rate"),
                            ("ai_analysis", "AI Analysis Success Rate"),
                            ("response_time", "Response Time"),
                        ],
                        max_length=30,
                        verbose_name="Metric Type",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Value")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Details"),
                ),
            ],
            options={
                "verbose_name": "System Health Metric",
                "verbose_name_plural": "System Health Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "timestamp"],
                        name="core_system_metric__33ae4e_idx",
                    )
                ],
            },
        ),
    ]
