# Generated by Django 5.0.1 on 2026-01-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_processingfailure_systemhealthmetric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("document_upload", "Document Upload"),
                    ("document_view", "Document View"),
                    ("document_download", "Document Download"),
                    ("document_delete", "Document Delete"),
                    ("pii_view", "PII View"),
                    ("pii_export", "PII Export"),
                    ("ai_analysis", "AI Analysis"),
                    ("denial_decode", "Denial Decode"),
                    ("ai_decision_analyzer", "Decision Letter Analysis"),
                    ("ai_evidence_gap", "Evidence Gap Analysis"),
                    ("ai_statement_generator", "Statement Generation"),
                    ("vso_case_create", "Case Created"),
                    ("vso_case_view", "Case Viewed"),
                    ("vso_case_update", "Case Updated"),
                    ("vso_document_share", "Document Shared"),
                    ("vso_document_review", "Document Reviewed"),
                    ("vso_note_add", "Case Note Added"),
                    ("vso_invitation_sent", "Invitation Sent"),
                    ("vso_invitation_accept", "Invitation Accepted"),
                    ("profile_update", "Profile Update"),
                    ("account_delete", "Account Delete Request"),
                    ("ai_consent_grant", "AI Consent Granted"),
                    ("ai_consent_revoke", "AI Consent Revoked"),
                    ("admin_action", "Admin Action"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Action",
            ),
        ),
    ]
