name: benefits-navigator-staging
region: nyc
features:
  - buildpack-stack=ubuntu-22

# App-level environment variables (inherited by all components)
envs:
  - key: DJANGO_SETTINGS_MODULE
    value: benefits_navigator.settings
  - key: DEBUG
    value: "False"
  - key: USE_S3
    value: "False"
  - key: STAGING
    value: "True"
  # Secrets - values must be set in DO Console after deploy
  - key: SECRET_KEY
    type: SECRET
  - key: REDIS_URL
    type: SECRET
  - key: CELERY_BROKER_URL
    type: SECRET
  - key: OPENAI_API_KEY
    type: SECRET
  - key: SENTRY_DSN
    type: SECRET

services:
  # Django Web Application
  - name: web
    github:
      repo: Beaudoin0zach/benefits_navigator
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile.prod
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /
    health_check:
      http_path: /health/
      initial_delay_seconds: 30
      period_seconds: 10
    envs:
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}

workers:
  # Celery Worker (background tasks)
  - name: worker
    github:
      repo: Beaudoin0zach/benefits_navigator
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile.prod
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: celery -A benefits_navigator worker -l info --concurrency=2
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}

databases:
  - name: db
    engine: PG
    num_nodes: 1
    size: db-s-dev-database
    version: "15"

# Secrets to set in DO Console (App-Level Environment Variables):
# - SECRET_KEY
# - VALKEY_URL (also as REDIS_URL and CELERY_BROKER_URL)
# - OPENAI_API_KEY
# - SENTRY_DSN
