name: benefits-navigator-staging
region: nyc
features:
  - buildpack-stack=ubuntu-22

services:
  # Django Web Application
  - name: web
    github:
      repo: Beaudoin0zach/benefits_navigator
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile.prod
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /
    health_check:
      http_path: /health/
      initial_delay_seconds: 30
      period_seconds: 10
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: benefits_navigator.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ${APP_DOMAIN}
      - key: SECRET_KEY
        type: SECRET
        value: "${SECRET_KEY}"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: CELERY_BROKER_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: OPENAI_API_KEY
        type: SECRET
        value: "${OPENAI_API_KEY}"
      - key: SENTRY_DSN
        value: "${SENTRY_DSN}"
      - key: USE_S3
        value: "False"

  # Celery Worker
  - name: worker
    github:
      repo: Beaudoin0zach/benefits_navigator
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile.prod
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: celery -A benefits_navigator worker -l info --concurrency=2
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: benefits_navigator.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "${SECRET_KEY}"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: CELERY_BROKER_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: OPENAI_API_KEY
        type: SECRET
        value: "${OPENAI_API_KEY}"

databases:
  - name: db
    engine: PG
    num_nodes: 1
    size: db-s-dev-database
    version: "15"

# Note: For Redis, you'll need to create a managed Redis cluster separately
# and add the connection string as an environment variable, OR use the
# DigitalOcean Managed Redis add-on when available in your region.
# Alternative: Use Redis Cloud free tier (30MB) for staging.
