# Generated by Django 5.0.1 on 2026-01-09 18:20

import claims.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text='e.g., "PTSD Service Connection" or "Knee Injury Increase"',
                        max_length=200,
                        verbose_name="Claim title",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Claim"),
                            ("increase", "Claim for Increase"),
                            ("secondary", "Secondary Condition"),
                            ("new_condition", "New Condition"),
                        ],
                        default="initial",
                        max_length=20,
                        verbose_name="Claim type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("gathering_evidence", "Gathering Evidence"),
                            ("submitted", "Submitted to VA"),
                            ("pending", "Pending VA Decision"),
                            ("decided", "Decision Received"),
                            ("appealed", "Under Appeal"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date submitted to VA"
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Decision received date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=claims.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png", "tiff"]
                            )
                        ],
                        verbose_name="Document file",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Original filename"),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="File size (bytes)"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("medical_records", "Medical Records"),
                            ("service_records", "Service Records / STRs"),
                            ("decision_letter", "VA Decision Letter"),
                            ("buddy_statement", "Buddy Statement"),
                            ("lay_statement", "Lay Statement"),
                            ("nexus_letter", "Medical Nexus/Opinion Letter"),
                            ("employment_records", "Employment Records"),
                            ("personal_statement", "Personal Statement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Document type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="Processing status",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Text extracted from document via OCR",
                        verbose_name="Extracted text",
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Average confidence score from OCR (0-100)",
                        null=True,
                        verbose_name="OCR confidence score",
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(default=0, verbose_name="Number of pages"),
                ),
                (
                    "ai_summary",
                    models.JSONField(
                        blank=True,
                        help_text="Structured analysis results from OpenAI",
                        null=True,
                        verbose_name="AI analysis summary",
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="AI model"
                    ),
                ),
                (
                    "ai_tokens_used",
                    models.IntegerField(default=0, verbose_name="Tokens used"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processing completed at"
                    ),
                ),
                (
                    "processing_duration",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Processing duration (seconds)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error message"),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Associate this document with a claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="claims.claim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="claims_docu_user_id_8d7c2e_idx"
                    ),
                    models.Index(
                        fields=["user", "document_type"],
                        name="claims_docu_user_id_4decbe_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="claims_docu_created_b65d58_idx"
                    ),
                ],
            },
        ),
    ]
