# Generated by Django 5.0.1 on 2026-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ocr_length",
            field=models.IntegerField(
                default=0,
                help_text="Character count of extracted text (metadata only, no PHI)",
                verbose_name="Extracted text length",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of OCR extraction process",
                max_length=20,
                verbose_name="OCR status",
            ),
        ),
    ]
