# Generated by Django 5.0.1 on 2026-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_add_ocr_metadata_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="ocr_text",
        ),
    ]
