# Generated by Django 5.2.10 on 2026-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_remove_ocr_text_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="condition_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of condition names this document relates to",
                verbose_name="Condition tags",
            ),
        ),
    ]
