# Generated by Django 5.0.1 on 2026-01-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch for all email notifications",
                        verbose_name="Enable email notifications",
                    ),
                ),
                (
                    "deadline_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Receive reminders about upcoming deadlines",
                        verbose_name="Deadline reminders",
                    ),
                ),
                (
                    "exam_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Receive reminders about upcoming C&P exams",
                        verbose_name="C&P exam reminders",
                    ),
                ),
                (
                    "claim_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Receive updates about claim status changes",
                        verbose_name="Claim status updates",
                    ),
                ),
                (
                    "weekly_summary",
                    models.BooleanField(
                        default=False,
                        help_text="Receive a weekly summary of your claims journey",
                        verbose_name="Weekly summary",
                    ),
                ),
                (
                    "deadline_reminder_days",
                    models.IntegerField(
                        choices=[
                            (30, "30 days before"),
                            (14, "14 days before"),
                            (7, "7 days before"),
                            (3, "3 days before"),
                            (1, "1 day before"),
                        ],
                        default=7,
                        help_text="How many days before a deadline to send reminder",
                        verbose_name="Remind me before deadline",
                    ),
                ),
                (
                    "exam_reminder_days",
                    models.IntegerField(
                        choices=[
                            (30, "30 days before"),
                            (14, "14 days before"),
                            (7, "7 days before"),
                            (3, "3 days before"),
                            (1, "1 day before"),
                        ],
                        default=7,
                        help_text="How many days before a C&P exam to send reminder",
                        verbose_name="Remind me before exam",
                    ),
                ),
                (
                    "last_email_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last email sent"
                    ),
                ),
                (
                    "emails_sent_count",
                    models.IntegerField(default=0, verbose_name="Total emails sent"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
    ]
