# Generated by Django 5.0.1 on 2026-01-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_organizationinvitation_usagetracking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreferences",
            name="document_analysis",
            field=models.BooleanField(
                default=True,
                help_text="Receive notification when document analysis is finished",
                verbose_name="Document analysis complete",
            ),
        ),
    ]
