# Generated by Django 5.0.1 on 2026-01-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_document_analysis_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_consent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user provided AI processing consent",
                null=True,
                verbose_name="AI consent date",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_processing_consent",
            field=models.BooleanField(
                default=False,
                help_text="User has consented to AI/OCR processing of their documents",
                verbose_name="AI processing consent",
            ),
        ),
    ]
