# Generated by Django 5.0.1 on 2026-01-18 01:16

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_ai_consent_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=core.encryption.EncryptedDateField(
                blank=True,
                help_text="Encrypted for privacy",
                max_length=255,
                null=True,
                verbose_name="Date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="va_file_number",
            field=core.encryption.EncryptedCharField(
                blank=True,
                help_text="Optional - Your VA claim number (encrypted)",
                max_length=255,
                verbose_name="VA file number",
            ),
        ),
    ]
