# Generated by Django 5.0.1 on 2026-01-18 01:16
"""
Data migration to encrypt existing PII data.

This migration encrypts any existing unencrypted data in:
- UserProfile.date_of_birth
- UserProfile.va_file_number

The encryption is idempotent - already encrypted values are skipped.
"""

from django.db import migrations


def encrypt_existing_data(apps, schema_editor):
    """
    Encrypt existing PII data that may have been stored unencrypted.

    Note: This runs after the field type changes, so the field's
    get_prep_value will automatically encrypt on save. We just need
    to re-save records that have data but aren't yet encrypted.
    """
    from core.encryption import FieldEncryption

    UserProfile = apps.get_model('accounts', 'UserProfile')
    db_alias = schema_editor.connection.alias

    # Get raw values directly from database
    from django.db import connection

    with connection.cursor() as cursor:
        # Encrypt va_file_number
        cursor.execute("""
            SELECT id, va_file_number
            FROM accounts_userprofile
            WHERE va_file_number IS NOT NULL
            AND va_file_number != ''
            AND length(va_file_number) < 100
        """)
        for profile_id, va_file_number in cursor.fetchall():
            encrypted = FieldEncryption.encrypt(va_file_number)
            cursor.execute(
                "UPDATE accounts_userprofile SET va_file_number = %s WHERE id = %s",
                [encrypted, profile_id]
            )

        # Encrypt date_of_birth (stored as date, needs conversion)
        cursor.execute("""
            SELECT id, date_of_birth
            FROM accounts_userprofile
            WHERE date_of_birth IS NOT NULL
        """)
        for profile_id, dob in cursor.fetchall():
            # Skip if already encrypted (would be a string starting with Z0FB)
            if isinstance(dob, str) and len(dob) > 50 and dob.startswith('Z0FB'):
                continue
            # Convert date to ISO string and encrypt
            if hasattr(dob, 'isoformat'):
                date_str = dob.isoformat()
            else:
                date_str = str(dob)
            encrypted = FieldEncryption.encrypt(date_str)
            cursor.execute(
                "UPDATE accounts_userprofile SET date_of_birth = %s WHERE id = %s",
                [encrypted, profile_id]
            )


def decrypt_data(apps, schema_editor):
    """
    Reverse migration - decrypt data back to plain text.

    WARNING: This should generally not be needed and loses the security benefit.
    """
    from core.encryption import FieldEncryption
    from django.db import connection

    with connection.cursor() as cursor:
        # Decrypt va_file_number
        cursor.execute("""
            SELECT id, va_file_number
            FROM accounts_userprofile
            WHERE va_file_number IS NOT NULL
            AND va_file_number != ''
            AND length(va_file_number) > 100
        """)
        for profile_id, va_file_number in cursor.fetchall():
            decrypted = FieldEncryption.decrypt(va_file_number)
            if decrypted:
                cursor.execute(
                    "UPDATE accounts_userprofile SET va_file_number = %s WHERE id = %s",
                    [decrypted, profile_id]
                )

        # Decrypt date_of_birth
        cursor.execute("""
            SELECT id, date_of_birth
            FROM accounts_userprofile
            WHERE date_of_birth IS NOT NULL
            AND date_of_birth != ''
        """)
        for profile_id, dob in cursor.fetchall():
            if isinstance(dob, str) and len(dob) > 50:
                decrypted = FieldEncryption.decrypt(dob)
                if decrypted:
                    cursor.execute(
                        "UPDATE accounts_userprofile SET date_of_birth = %s WHERE id = %s",
                        [decrypted, profile_id]
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_encrypt_pii_fields"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_data, decrypt_data),
    ]
