# Generated by Django 5.0.1 on 2026-01-11 18:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g., 'document-text' for Heroicons)",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Document Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LegalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("cavc", "CAVC Decision"),
                            ("vaopgcprec", "VA General Counsel Opinion"),
                            ("cfr", "Code of Federal Regulations"),
                            ("statute", "U.S. Code/Statute"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "citation",
                    models.CharField(
                        help_text="Full legal citation (e.g., 'Caluza v. Brown, 7 Vet. App. 498 (1995)')",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short reference name (e.g., 'Caluza')",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title of what this reference establishes",
                        max_length=300,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Plain-language summary of the holding/opinion"
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        default=list, help_text="Bullet points of key takeaways"
                    ),
                ),
                (
                    "relevance",
                    models.TextField(
                        help_text="When and how this applies to VA claims"
                    ),
                ),
                ("date_issued", models.DateField()),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to the full decision/opinion"
                    ),
                ),
                (
                    "related_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Conditions this reference is particularly relevant to",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this reference is still good law",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="If overruled, link to the superseding reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="documentation.legalreference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Reference",
                "verbose_name_plural": "Legal References",
                "ordering": ["-date_issued"],
            },
        ),
        migrations.CreateModel(
            name="VAForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_number",
                    models.CharField(
                        help_text="VA form number (e.g., '21-526EZ')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of what this form is used for"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Simplified instructions for completing the form"
                    ),
                ),
                (
                    "official_url",
                    models.URLField(help_text="Link to the official VA form PDF"),
                ),
                (
                    "instructions_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to official VA instructions (if separate)",
                    ),
                ),
                (
                    "workflow_stages",
                    models.JSONField(
                        default=list,
                        help_text="List of workflow stages where this form is used",
                    ),
                ),
                (
                    "deadline_info",
                    models.TextField(
                        blank=True, help_text="Deadline requirements and time limits"
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        blank=True,
                        help_text="User-friendly tips for completing the form",
                    ),
                ),
                (
                    "common_mistakes",
                    models.TextField(
                        blank=True,
                        help_text="Common mistakes to avoid when filling out this form",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this form is currently in use by VA",
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(help_text="When this form was last updated by VA"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forms",
                        to="documentation.documentcategory",
                    ),
                ),
                (
                    "related_forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other forms commonly used together",
                        to="documentation.vaform",
                    ),
                ),
            ],
            options={
                "verbose_name": "VA Form",
                "verbose_name_plural": "VA Forms",
                "ordering": ["form_number"],
            },
        ),
        migrations.CreateModel(
            name="CPExamGuideCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(
                        help_text="Name of the medical condition (e.g., 'PTSD', 'Sleep Apnea')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mental_health", "Mental Health"),
                            ("musculoskeletal", "Musculoskeletal"),
                            ("respiratory", "Respiratory"),
                            ("cardiovascular", "Cardiovascular"),
                            ("neurological", "Neurological"),
                            ("auditory", "Auditory/Hearing"),
                            ("digestive", "Digestive"),
                            ("skin", "Skin"),
                            ("endocrine", "Endocrine"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "dbq_form",
                    models.CharField(
                        blank=True,
                        help_text="Associated Disability Benefits Questionnaire number",
                        max_length=50,
                    ),
                ),
                (
                    "what_to_expect",
                    models.TextField(
                        help_text="Description of what happens during the C&P exam"
                    ),
                ),
                (
                    "key_questions",
                    models.JSONField(
                        default=list,
                        help_text="List of questions the examiner will likely ask",
                    ),
                ),
                (
                    "documentation_needed",
                    models.JSONField(
                        default=list,
                        help_text="Documents you should bring to the exam",
                    ),
                ),
                (
                    "how_to_prepare",
                    models.TextField(help_text="Steps to prepare for the examination"),
                ),
                ("tips", models.TextField(help_text="Helpful tips for the exam")),
                (
                    "red_flags",
                    models.TextField(
                        blank=True, help_text="Common mistakes or things to avoid"
                    ),
                ),
                (
                    "rating_criteria_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of how VA rates this condition",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "related_conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related conditions often claimed together",
                        to="documentation.cpexamguidecondition",
                    ),
                ),
                (
                    "related_form",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary form used for this condition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_guides",
                        to="documentation.vaform",
                    ),
                ),
            ],
            options={
                "verbose_name": "C&P Exam Guide",
                "verbose_name_plural": "C&P Exam Guides",
                "ordering": ["category", "condition_name"],
            },
        ),
        migrations.AddIndex(
            model_name="legalreference",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="documentati_search__a7b3c4_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="vaform",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="documentati_search__f12e89_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="cpexamguidecondition",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="documentati_search__d45a12_gin"
            ),
        ),
    ]
