# Generated by Django 5.0.1 on 2026-01-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cpexamguidecondition",
            new_name="documentati_search__ac6a68_gin",
            old_name="documentati_search__d45a12_gin",
        ),
        migrations.RenameIndex(
            model_name="legalreference",
            new_name="documentati_search__4e937f_gin",
            old_name="documentati_search__a7b3c4_gin",
        ),
        migrations.RenameIndex(
            model_name="vaform",
            new_name="documentati_search__a367b2_gin",
            old_name="documentati_search__f12e89_gin",
        ),
    ]
