# Generated by Django 5.0.1 on 2026-01-09 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealGuidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="URL slug")),
                (
                    "appeal_type",
                    models.CharField(
                        choices=[
                            ("hlr", "Higher-Level Review"),
                            ("supplemental", "Supplemental Claim"),
                            ("board", "Board Appeal"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Appeal Type",
                    ),
                ),
                (
                    "va_form_number",
                    models.CharField(
                        help_text="e.g., VA Form 20-0995",
                        max_length=50,
                        verbose_name="VA Form Number",
                    ),
                ),
                (
                    "average_processing_days",
                    models.IntegerField(
                        help_text="Average time from submission to decision",
                        verbose_name="Average Processing Time (days)",
                    ),
                ),
                (
                    "when_to_use",
                    models.TextField(
                        help_text="Criteria for choosing this appeal path",
                        verbose_name="When to Use This Appeal Type",
                    ),
                ),
                (
                    "when_not_to_use",
                    models.TextField(
                        help_text="Situations where another appeal type is better",
                        verbose_name="When NOT to Use This Appeal Type",
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        help_text="Plain-language explanation of this appeal type",
                        verbose_name="Overview",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        help_text="What you need to file this appeal",
                        verbose_name="Requirements",
                    ),
                ),
                (
                    "step_by_step",
                    models.TextField(
                        help_text="Detailed steps to complete this appeal",
                        verbose_name="Step-by-Step Process",
                    ),
                ),
                (
                    "evidence_guidance",
                    models.TextField(
                        blank=True,
                        help_text="What evidence to include (or not)",
                        verbose_name="Evidence Guidance",
                    ),
                ),
                (
                    "common_mistakes",
                    models.TextField(
                        help_text="What veterans often get wrong",
                        verbose_name="Common Mistakes",
                    ),
                ),
                (
                    "after_submission",
                    models.TextField(
                        help_text="What to expect after filing",
                        verbose_name="After Submission",
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        help_text="Pro tips from VSOs and veterans",
                        verbose_name="Tips for Success",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        default=list,
                        help_text="Steps to complete before filing",
                        verbose_name="Preparation Checklist",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display order")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
            ],
            options={
                "verbose_name": "Appeal Guidance",
                "verbose_name_plural": "Appeal Guidance",
                "ordering": ["order", "appeal_type"],
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appeal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hlr", "Higher-Level Review"),
                            ("supplemental", "Supplemental Claim"),
                            ("board_direct", "Board Appeal - Direct Review"),
                            ("board_evidence", "Board Appeal - Evidence Submission"),
                            ("board_hearing", "Board Appeal - Hearing Request"),
                        ],
                        help_text="Type of appeal being filed",
                        max_length=20,
                        verbose_name="Appeal type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("deciding", "Deciding Appeal Path"),
                            ("gathering", "Gathering Materials"),
                            ("preparing", "Preparing Submission"),
                            ("ready", "Ready to Submit"),
                            ("submitted", "Submitted to VA"),
                            ("acknowledged", "VA Acknowledged Receipt"),
                            ("in_review", "Under VA Review"),
                            ("decision_pending", "Decision Pending"),
                            ("decided", "Decision Received"),
                            ("closed", "Closed"),
                        ],
                        default="deciding",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "original_decision_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the VA decision being appealed",
                        null=True,
                        verbose_name="Original Decision Date",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline to file this appeal (auto-calculated)",
                        null=True,
                        verbose_name="Filing Deadline",
                    ),
                ),
                (
                    "conditions_appealed",
                    models.TextField(
                        blank=True,
                        help_text="List the conditions/ratings you are appealing",
                        verbose_name="Conditions Being Appealed",
                    ),
                ),
                (
                    "denial_reasons",
                    models.TextField(
                        blank=True,
                        help_text="Why was your claim denied or rated low?",
                        verbose_name="Reasons for Denial/Low Rating",
                    ),
                ),
                (
                    "has_new_evidence",
                    models.BooleanField(
                        blank=True,
                        help_text="Evidence VA has not seen before",
                        null=True,
                        verbose_name="Do you have new evidence?",
                    ),
                ),
                (
                    "believes_va_error",
                    models.BooleanField(
                        blank=True,
                        help_text="Error based on existing evidence",
                        null=True,
                        verbose_name="Do you believe VA made an error?",
                    ),
                ),
                (
                    "wants_hearing",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Do you want to present your case in person?",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1,
                        help_text="Current step in the appeal process",
                        verbose_name="Current Step",
                    ),
                ),
                (
                    "workflow_state",
                    models.JSONField(
                        default=dict,
                        help_text="Tracks completed steps and data",
                        verbose_name="Workflow State",
                    ),
                ),
                (
                    "steps_completed",
                    models.JSONField(
                        default=list,
                        help_text="List of completed step IDs",
                        verbose_name="Completed Steps",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submission Date"
                    ),
                ),
                (
                    "va_confirmation_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="VA Confirmation Number",
                    ),
                ),
                (
                    "decision_received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Decision Received Date"
                    ),
                ),
                (
                    "decision_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("granted", "Granted (Favorable)"),
                            ("partial", "Partially Granted"),
                            ("denied", "Denied"),
                            ("remanded", "Remanded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Decision Outcome",
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Decision Notes"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Personal Notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal",
                "verbose_name_plural": "Appeals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppealDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("decision_letter", "VA Decision Letter"),
                            ("new_evidence", "New Evidence"),
                            ("medical_record", "Medical Record"),
                            ("nexus_letter", "Nexus Letter"),
                            ("buddy_statement", "Buddy Statement"),
                            ("personal_statement", "Personal Statement"),
                            ("form", "VA Form"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="appeals/documents/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=False, verbose_name="Included in Submission"
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="appeals.appeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal Document",
                "verbose_name_plural": "Appeal Documents",
                "ordering": ["document_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppealNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("user", "User Note"),
                            ("status", "Status Update"),
                            ("reminder", "Reminder"),
                            ("va_communication", "VA Communication"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="Note Type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_important",
                    models.BooleanField(
                        default=False, verbose_name="Mark as Important"
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_notes",
                        to="appeals.appeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal Note",
                "verbose_name_plural": "Appeal Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
