# Generated by Django 5.2.10 on 2026-01-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0001_initial"),
        ("vso", "0007_add_exam_tracking_and_case_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="veteran_case",
            field=models.ForeignKey(
                blank=True,
                help_text="VSO case this appeal is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeals",
                to="vso.veterancase",
            ),
        ),
    ]
