# Generated by Django 5.0.1 on 2026-01-18 00:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_add_ai_consent_fields"),
        ("agents", "0004_add_rating_analysis_model"),
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Case Checklist",
                "verbose_name_plural": "Case Checklists",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("form", "VA Form"),
                            ("medical", "Medical Evidence"),
                            ("statement", "Statement"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "visible_to_veteran",
                    models.BooleanField(
                        default=True,
                        help_text="Whether veteran sees this in their checklist",
                        verbose_name="Visible to veteran",
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vso.casechecklist",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_items",
                        to="claims.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Item",
                "verbose_name_plural": "Checklist Items",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="VeteranCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the case",
                        max_length=200,
                        verbose_name="Case title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed notes about the case",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("gathering_evidence", "Gathering Evidence"),
                            ("claim_filed", "Claim Filed"),
                            ("pending_decision", "Pending VA Decision"),
                            ("decision_received", "Decision Received"),
                            ("appeal_in_progress", "Appeal in Progress"),
                            ("closed_won", "Closed - Won"),
                            ("closed_denied", "Closed - Denied"),
                            ("closed_withdrawn", "Closed - Withdrawn"),
                            ("on_hold", "On Hold"),
                        ],
                        default="intake",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of conditions being claimed",
                        verbose_name="Conditions",
                    ),
                ),
                (
                    "intake_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Intake date"
                    ),
                ),
                (
                    "claim_filed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Claim filed date"
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Decision date"
                    ),
                ),
                (
                    "appeal_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Appeal deadline"
                    ),
                ),
                (
                    "next_action_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next action date"
                    ),
                ),
                (
                    "initial_combined_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating at start of case",
                        null=True,
                        verbose_name="Initial combined rating",
                    ),
                ),
                (
                    "final_combined_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating at end of case",
                        null=True,
                        verbose_name="Final combined rating",
                    ),
                ),
                (
                    "retroactive_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Retroactive compensation awarded",
                        max_digits=12,
                        null=True,
                        verbose_name="Retroactive pay",
                    ),
                ),
                (
                    "veteran_consent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When veteran consented to VSO access",
                        null=True,
                        verbose_name="Consent date",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed at"
                    ),
                ),
                (
                    "closure_notes",
                    models.TextField(blank=True, verbose_name="Closure notes"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="VSO caseworker assigned to this case",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consent_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Uploaded VA Form 21-22 or 21-22a",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_cases",
                        to="claims.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="accounts.organization",
                    ),
                ),
                (
                    "veteran",
                    models.ForeignKey(
                        help_text="The veteran this case is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vso_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Veteran Case",
                "verbose_name_plural": "Veteran Cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Shared at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("action_needed", "Action Needed"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed at"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Review notes"),
                ),
                (
                    "include_ai_analysis",
                    models.BooleanField(
                        default=True,
                        help_text="Share AI analysis results with VSO",
                        verbose_name="Include AI analysis",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_shares",
                        to="claims.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_documents",
                        to="vso.veterancase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Document",
                "verbose_name_plural": "Shared Documents",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("rating_analysis", "Rating Analysis"),
                            ("denial_decoding", "Denial Decoding"),
                            ("decision_analysis", "Decision Letter Analysis"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Shared at"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed at"
                    ),
                ),
                (
                    "vso_notes",
                    models.TextField(
                        blank=True,
                        help_text="VSO notes and recommendations based on analysis",
                        verbose_name="VSO notes",
                    ),
                ),
                (
                    "decision_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_shares",
                        to="agents.decisionletteranalysis",
                    ),
                ),
                (
                    "denial_decoding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_shares",
                        to="agents.denialdecoding",
                    ),
                ),
                (
                    "rating_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_shares",
                        to="agents.ratinganalysis",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_analyses",
                        to="vso.veterancase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Analysis",
                "verbose_name_plural": "Shared Analyses",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General Note"),
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("document_review", "Document Review"),
                            ("action_item", "Action Item"),
                            ("milestone", "Milestone"),
                            ("veteran_update", "Veteran Update"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_action_item",
                    models.BooleanField(default=False, verbose_name="Is action item"),
                ),
                (
                    "action_due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "action_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "action_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "visible_to_veteran",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the veteran can see this note",
                        verbose_name="Visible to veteran",
                    ),
                ),
                (
                    "action_completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="vso.veterancase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Note",
                "verbose_name_plural": "Case Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="casechecklist",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklists",
                to="vso.veterancase",
            ),
        ),
        migrations.AddIndex(
            model_name="veterancase",
            index=models.Index(
                fields=["organization", "status"], name="vso_veteran_organiz_6364c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veterancase",
            index=models.Index(
                fields=["assigned_to", "status"], name="vso_veteran_assigne_c6d549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veterancase",
            index=models.Index(
                fields=["veteran", "organization"],
                name="vso_veteran_veteran_538de4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shareddocument",
            unique_together={("case", "document")},
        ),
    ]
