# Generated by Django 5.0.1 on 2026-01-21 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_encrypt_existing_pii_data"),
        ("claims", "0001_initial"),
        ("vso", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_name",
                    models.CharField(max_length=200, verbose_name="Condition Name"),
                ),
                (
                    "diagnostic_code",
                    models.CharField(
                        blank=True,
                        help_text="VA diagnostic code (e.g., 9411 for PTSD)",
                        max_length=20,
                        verbose_name="Diagnostic Code",
                    ),
                ),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("gathering_evidence", "Gathering Evidence"),
                            ("evidence_complete", "Evidence Complete"),
                            ("claim_filed", "Claim Filed"),
                            ("pending_decision", "Pending Decision"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("appealing", "Appealing"),
                        ],
                        default="identified",
                        max_length=30,
                        verbose_name="Workflow Status",
                    ),
                ),
                (
                    "current_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Current VA rating percentage (0-100)",
                        null=True,
                        verbose_name="Current Rating",
                    ),
                ),
                (
                    "target_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Target rating percentage for this claim",
                        null=True,
                        verbose_name="Target Rating",
                    ),
                ),
                (
                    "service_connection_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "Direct Service Connection"),
                            ("secondary", "Secondary Service Connection"),
                            ("presumptive", "Presumptive"),
                            ("aggravation", "Aggravation"),
                        ],
                        max_length=30,
                        verbose_name="Service Connection Type",
                    ),
                ),
                (
                    "has_diagnosis",
                    models.BooleanField(
                        default=False,
                        help_text="Medical diagnosis documentation exists",
                        verbose_name="Has Diagnosis",
                    ),
                ),
                (
                    "has_in_service_event",
                    models.BooleanField(
                        default=False,
                        help_text="Service treatment records or incident documentation exists",
                        verbose_name="Has In-Service Event",
                    ),
                ),
                (
                    "has_nexus",
                    models.BooleanField(
                        default=False,
                        help_text="Medical opinion linking condition to service exists",
                        verbose_name="Has Nexus",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Added"),
                            ("rating_analysis", "Rating Analysis"),
                            ("decision_analysis", "Decision Letter Analysis"),
                        ],
                        default="manual",
                        max_length=30,
                        verbose_name="Source",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Case Condition",
                "verbose_name_plural": "Case Conditions",
                "ordering": ["condition_name"],
            },
        ),
        migrations.AddField(
            model_name="veterancase",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Archived At"
            ),
        ),
        migrations.AddField(
            model_name="veterancase",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AddField(
            model_name="veterancase",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Activity"
            ),
        ),
        migrations.AddIndex(
            model_name="veterancase",
            index=models.Index(
                fields=["last_activity_at"], name="vso_veteran_last_ac_f9b598_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veterancase",
            index=models.Index(
                fields=["is_archived"], name="vso_veteran_is_arch_4cd393_idx"
            ),
        ),
        migrations.AddField(
            model_name="casecondition",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_conditions",
                to="vso.veterancase",
            ),
        ),
        migrations.AddField(
            model_name="casecondition",
            name="source_analysis",
            field=models.ForeignKey(
                blank=True,
                help_text="The analysis this condition was derived from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_conditions",
                to="vso.sharedanalysis",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casecondition",
            unique_together={("case", "condition_name")},
        ),
    ]
