# Generated by Django 5.0.1 on 2026-01-21 00:28

from django.db import migrations


def backfill_last_activity(apps, schema_editor):
    """
    Backfill last_activity_at for existing cases.

    Uses the most recent of:
    - Case updated_at
    - Most recent CaseNote created_at
    - Most recent SharedDocument shared_at
    - Most recent SharedAnalysis shared_at
    """
    VeteranCase = apps.get_model('vso', 'VeteranCase')
    CaseNote = apps.get_model('vso', 'CaseNote')
    SharedDocument = apps.get_model('vso', 'SharedDocument')
    SharedAnalysis = apps.get_model('vso', 'SharedAnalysis')

    for case in VeteranCase.objects.filter(last_activity_at__isnull=True):
        # Start with the case's updated_at
        last_activity = case.updated_at

        # Check for more recent notes
        latest_note = CaseNote.objects.filter(case=case).order_by('-created_at').first()
        if latest_note and latest_note.created_at > last_activity:
            last_activity = latest_note.created_at

        # Check for more recent shared documents
        latest_doc = SharedDocument.objects.filter(case=case).order_by('-shared_at').first()
        if latest_doc and latest_doc.shared_at > last_activity:
            last_activity = latest_doc.shared_at

        # Check for more recent shared analyses
        latest_analysis = SharedAnalysis.objects.filter(case=case).order_by('-shared_at').first()
        if latest_analysis and latest_analysis.shared_at > last_activity:
            last_activity = latest_analysis.shared_at

        case.last_activity_at = last_activity
        case.save(update_fields=['last_activity_at'])


def reverse_backfill(apps, schema_editor):
    """Reverse operation - set all last_activity_at to NULL."""
    VeteranCase = apps.get_model('vso', 'VeteranCase')
    VeteranCase.objects.all().update(last_activity_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("vso", "0002_add_case_lifecycle_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_last_activity, reverse_backfill),
    ]
