# Generated by Django 5.0.1 on 2026-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vso", "0003_backfill_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareddocument",
            name="include_ai_analysis",
            field=models.BooleanField(
                default=False,
                help_text="Explicitly share AI analysis results with VSO (opt-in)",
                verbose_name="Include AI analysis",
            ),
        ),
    ]
