# Generated by Django 5.0.1 on 2026-01-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_encrypt_existing_pii_data"),
        ("vso", "0004_change_include_ai_analysis_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedanalysis",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (auto-populated from case for defense-in-depth)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_analyses",
                to="accounts.organization",
            ),
        ),
    ]
