# Generated by Django 5.2.10 on 2026-01-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vso", "0006_backfill_sharedanalysis_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterancase",
            name="c_and_p_exam_date",
            field=models.DateField(
                blank=True,
                help_text="Scheduled Compensation & Pension exam date",
                null=True,
                verbose_name="C&P Exam Date",
            ),
        ),
        migrations.AddField(
            model_name="veterancase",
            name="c_and_p_exam_location",
            field=models.CharField(
                blank=True,
                help_text="Location/facility for the exam",
                max_length=255,
                verbose_name="C&P Exam Location",
            ),
        ),
        migrations.AddField(
            model_name="veterancase",
            name="c_and_p_exam_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the exam (conditions being evaluated, etc.)",
                verbose_name="C&P Exam Notes",
            ),
        ),
    ]
